print("Welcome to your Bank \n LOGIN DETAILS")
Name=input("Hello, please enter your Name\n")
Byear=int(input("Please enter your birthyear"))
Age=str(2021-Byear)
print("Hello, Mr. "+Name+"You are "+Age+" Thank you for logging in."+ Name[0:4])
